In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df = pd.read_csv("unemployment analysis.csv", delimiter=",")

In [22]:
df2 = pd.read_csv("country_code.csv", delimiter=",")

In [25]:
left  = pd.merge(df, df2, how="left", on='Country Code')

In [29]:
left

,Country Name,Country Code,1991,1992,1993,1994,1995,1996,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,Unnamed: 0,Country_name,code_2digit
0,Africa Eastern and Southern,AFE,7.80,7.84,7.85,7.84,7.83,7.84,7.86,7.81,...,6.49,6.61,6.71,6.73,6.91,7.56,8.11,NaN,NaN,NaN
1,Afghanistan,AFG,10.65,10.82,10.72,10.73,11.18,10.96,10.78,10.80,...,11.13,11.16,11.18,11.15,11.22,11.71,13.28,2.0,Afghanistan,AF
2,Africa Western and Central,AFW,4.42,4.53,4.55,4.54,4.53,4.57,4.60,4.66,...,4.63,5.57,6.02,6.04,6.06,6.77,6.84,NaN,NaN,NaN
3,Angola,AGO,4.21,4.21,4.23,4.16,4.11,4.10,4.09,4.07,...,7.39,7.41,7.41,7.42,7.42,8.33,8.53,8.0,Angola,AO
4,Albania,ALB,10.31,30.01,25.26,20.84,14.61,13.93,16.88,20.05,...,17.19,15.42,13.62,12.30,11.47,13.33,11.82,4.0,Albania,AL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,Samoa,WSM,2.10,2.38,2.63,3.04,3.19,3.47,3.90,4.18,...,8.50,8.31,8.58,8.69,8.41,9.15,9.84,193.0,Samoa,WS
231,"Yemen, Rep.",YEM,8.32,8.31,8.35,8.34,8.96,9.59,10.20,10.81,...,13.77,13.43,13.30,13.15,13.06,13.39,13.57,246.0,Yemen,YE
232,South Africa,ZAF,29.95,29.98,29.92,29.89,29.89,29.87,29.91,29.95,...,25.15,26.54,27.04,26.91,28.47,29.22,33.56,206.0,South Africa,ZA
233,Zambia,ZMB,18.90,19.37,19.70,18.43,16.81,15.30,13.64,12.00,...,10.13,10.87,11.63,12.01,12.52,12.85,13.03,247.0,Zambia,ZM
234,Zimbabwe,ZWE,4.94,4.99,4.97,4.96,5.63,6.25,6.93,6.46,...,4.78,4.79,4.78,4.80,4.83,5.35,5.17,248.0,Zimbabwe,ZW